export const LITERALS = {
  expenses: 'Gastos',
  expense: 'Gasto',
  revenues: 'Ingresos',
  revenue: 'Ingreso',
  totalRevenue: 'Total ingresado',
  totalExpense: 'Total gastado',
  totalMoney: 'Total dinero',
  categories: {
    food: 'Comida',
    home: 'Hogar',
    finances: 'Finanzas',
    work: 'Trabajo',
    entertainment: 'Entretenimiento',
  },
  amount: 'Importe',
  description: 'Descripción',
  create: 'Crear',
  saveChanges: 'Guardar cambios',
  delete: 'Borrar',
  showMore: 'Ver más',
  transactions: 'Transacciones',
  yes: 'Sí',
  no: 'No',
  routes: {
    home: 'inicio',
    registration: 'registro',
    login: 'login',
    slash: '/',
  },
  name: 'Nombre',
  firstSurname: 'Primer apellido',
  secondSurname: 'Segundo apellido',
  email: 'Correo electrónico',
  password: 'Contraseña',
  confirmPassword: 'Confirmar contraseña',
  login: 'Iniciar sesión',
};
